import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { addExpense, addIncome } from '../src/db';
const clean=v=>Number(String(v||'').replace(/[^0-9]/g,''));
export default function Add(){
 const r=useRouter(),params=useLocalSearchParams(); const [type,setType]=useState(params.type==='expense'?'expense':'income'); const [title,setTitle]=useState(''); const [amount,setAmount]=useState('');
 const save=async()=>{const n=clean(amount); if(!title||!n)return Alert.alert('Data belum lengkap','Isi nama dan nominal terlebih dahulu.'); try{if(type==='income') await addIncome({title,amount:n,date:new Date().toISOString().slice(0,10)}); else await addExpense({title,amount:n}); r.back();}catch(e){Alert.alert('Tidak dapat menyimpan',e.message)}};
 return <View style={s.page}><View style={s.head}><Pressable onPress={()=>r.back()}><Ionicons name="close" size={26} color="#101828"/></Pressable><Text style={s.title}>Tambah transaksi</Text><View style={{width:26}}/></View><Text style={s.label}>JENIS</Text><View style={s.segment}><Pressable onPress={()=>setType('income')} style={[s.seg,type==='income'&&s.segActive]}><Text style={[s.segText,type==='income'&&s.segTextActive]}>Pemasukan</Text></Pressable><Pressable onPress={()=>setType('expense')} style={[s.seg,type==='expense'&&s.segActive]}><Text style={[s.segText,type==='expense'&&s.segTextActive]}>Pengeluaran</Text></Pressable></View><Text style={s.label}>KETERANGAN</Text><TextInput value={title} onChangeText={setTitle} placeholder={type==='income'?'Contoh: Gaji Oktober':'Contoh: Belanja rumah'} style={s.input}/><Text style={s.label}>NOMINAL</Text><TextInput value={amount} onChangeText={setAmount} keyboardType="number-pad" placeholder="Rp 0" style={s.input}/><Pressable style={s.primary} onPress={save}><Text style={s.primaryText}>Simpan transaksi</Text></Pressable></View>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F8FAFC',padding:20,paddingTop:54},head:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:28},title:{fontSize:20,fontWeight:'800',color:'#101828'},label:{fontSize:11,fontWeight:'800',letterSpacing:.7,color:'#667085',marginTop:18,marginBottom:8},segment:{backgroundColor:'#EAECF0',padding:4,borderRadius:14,flexDirection:'row'},seg:{flex:1,padding:12,alignItems:'center',borderRadius:11},segActive:{backgroundColor:'#fff'},segText:{fontWeight:'700',color:'#667085'},segTextActive:{color:'#155EEF'},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#D0D5DD',borderRadius:14,padding:14,fontSize:15,color:'#101828'},primary:{backgroundColor:'#155EEF',padding:16,borderRadius:15,alignItems:'center',marginTop:30},primaryText:{color:'#fff',fontWeight:'800',fontSize:15}});
