import { useCallback, useState } from 'react';
import { ScrollView, StyleSheet, Text, View, Pressable, RefreshControl } from 'react-native';
import { useFocusEffect, useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { dashboard, listDebts, listReceivables, listSavings, listTransactions } from '../../src/db';
const rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n||0);
const month=new Intl.DateTimeFormat('id-ID',{month:'long',year:'numeric'}).format(new Date());
export default function Home(){
 const r=useRouter(),[data,setData]=useState({}),[debts,setDebts]=useState([]),[recv,setRecv]=useState([]),[sav,setSav]=useState([]),[tx,setTx]=useState([]),[refresh,setRefresh]=useState(false);
 const load=async()=>{setRefresh(true);try{const [d,a,b,c,e]=await Promise.all([dashboard(),listDebts(),listReceivables(),listSavings(),listTransactions()]);setData(d);setDebts(a);setRecv(b);setSav(c);setTx(e)}finally{setRefresh(false)}};
 useFocusEffect(useCallback(()=>{load()},[]));
 const activeDebt=debts.filter(x=>x.status==='active');
 return <ScrollView style={s.page} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refresh} onRefresh={load}/>}> 
  <View style={s.top}><View><Text style={s.greeting}>Keuangan Saya</Text><Text style={s.date}>{month}</Text></View><Pressable style={s.iconBtn} onPress={()=>r.push('/add')}><Ionicons name="add" size={22} color="#155EEF"/></Pressable></View>
  <View style={s.hero}><View style={s.heroHead}><Text style={s.heroLabel}>TOTAL DEPOSIT</Text><Ionicons name="eye-outline" size={20} color="#D0D5DD"/></View><Text style={s.heroAmount}>{rupiah(data.balance)}</Text><View style={s.heroBottom}><View><Text style={s.heroSmall}>Gaji bulan ini</Text><Text style={s.heroValue}>{rupiah(data.income)}</Text></View><View style={s.heroBadge}><Ionicons name="trending-up" size={14} color="#12B76A"/><Text style={s.heroBadgeText}>Aktif</Text></View></View></View>
  <View style={s.cards}><Metric icon="card-outline" label="Utang" value={data.debt} tone="#F04438"/><Metric icon="people-outline" label="Piutang" value={data.receivable} tone="#12B76A"/><Metric icon="wallet-outline" label="Tabungan" value={data.savings} tone="#155EEF"/></View>
  <Text style={s.section}>Aksi cepat</Text><View style={s.quickRow}><Quick icon="cash-outline" label="Gaji" onPress={()=>r.push('/add?type=income')}/><Quick icon="card-outline" label="Utang" onPress={()=>r.push('/debt')}/><Quick icon="people-outline" label="Piutang" onPress={()=>r.push('/receivable')}/><Quick icon="wallet-outline" label="Tabungan" onPress={()=>r.push('/savings')}/></View>
  <View style={s.sectionHead}><Text style={s.section}>Jatuh tempo</Text><Pressable onPress={()=>r.push('/(tabs)/debts')}><Text style={s.link}>Lihat semua</Text></Pressable></View>
  {activeDebt.slice(0,3).map(x=><View style={s.item} key={x.id}><View style={s.itemIcon}><Ionicons name="calendar-outline" size={19} color="#F04438"/></View><View style={s.itemMain}><Text style={s.itemTitle}>{x.name}</Text><Text style={s.itemSub}>{x.terms_remaining} tempo tersisa {x.due_day?`• tanggal ${x.due_day}`:''}</Text></View><Text style={s.itemAmount}>{rupiah(x.remaining)}</Text></View>)}
  {!activeDebt.length&&<Empty text="Belum ada utang aktif."/>}
  <View style={s.sectionHead}><Text style={s.section}>Transaksi terakhir</Text><Pressable onPress={()=>r.push('/(tabs)/transactions')}><Text style={s.link}>Semua</Text></Pressable></View>
  {tx.slice(0,4).map(x=><View style={s.item} key={x.id}><View style={[s.itemIcon,{backgroundColor:x.type==='income'||x.type==='receivable_payment'?'#ECFDF3':'#FEF3F2'}]}><Ionicons name={x.type==='income'||x.type==='receivable_payment'?'arrow-down':'arrow-up'} size={18} color={x.type==='income'||x.type==='receivable_payment'?'#12B76A':'#F04438'}/></View><View style={s.itemMain}><Text style={s.itemTitle}>{x.title}</Text><Text style={s.itemSub}>{x.date}</Text></View><Text style={[s.itemAmount,{color:x.type==='income'||x.type==='receivable_payment'?'#12B76A':'#101828'}]}>{x.type==='income'||x.type==='receivable_payment'?'+':'-'}{rupiah(x.amount)}</Text></View>)}
  {!tx.length&&<Empty text="Belum ada transaksi."/>}
 </ScrollView>
}
function Metric({icon,label,value,tone}){return <View style={s.metric}><View style={[s.metricIcon,{backgroundColor:tone+'18'}]}><Ionicons name={icon} size={18} color={tone}/></View><Text style={s.metricLabel}>{label}</Text><Text style={s.metricValue}>{rupiah(value)}</Text></View>}
function Quick({icon,label,onPress}){return <Pressable style={s.quick} onPress={onPress}><View style={s.quickIcon}><Ionicons name={icon} size={21} color="#155EEF"/></View><Text style={s.quickText}>{label}</Text></Pressable>}
function Empty({text}){return <View style={s.empty}><Text style={s.emptyText}>{text}</Text></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F8FAFC'},content:{padding:20,paddingTop:54,paddingBottom:30},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:18},greeting:{fontSize:27,fontWeight:'800',color:'#101828'},date:{fontSize:13,color:'#667085',marginTop:3},iconBtn:{width:44,height:44,borderRadius:14,backgroundColor:'#EFF4FF',alignItems:'center',justifyContent:'center'},hero:{backgroundColor:'#101828',borderRadius:24,padding:21,marginBottom:12},heroHead:{flexDirection:'row',justifyContent:'space-between'},heroLabel:{color:'#98A2B3',fontSize:11,fontWeight:'800',letterSpacing:1},heroAmount:{color:'#fff',fontSize:31,fontWeight:'800',marginTop:7},heroBottom:{marginTop:18,flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end'},heroSmall:{color:'#98A2B3',fontSize:12},heroValue:{color:'#fff',fontWeight:'700',marginTop:3},heroBadge:{flexDirection:'row',gap:5,alignItems:'center',backgroundColor:'#ECFDF3',paddingHorizontal:9,paddingVertical:5,borderRadius:20},heroBadgeText:{color:'#067647',fontWeight:'700',fontSize:11},cards:{flexDirection:'row',gap:8},metric:{flex:1,backgroundColor:'#fff',borderRadius:16,padding:13,borderWidth:1,borderColor:'#EAECF0'},metricIcon:{width:32,height:32,borderRadius:10,alignItems:'center',justifyContent:'center'},metricLabel:{fontSize:11,color:'#667085',marginTop:9},metricValue:{fontSize:13,fontWeight:'800',color:'#101828',marginTop:3},section:{fontSize:18,fontWeight:'800',color:'#101828',marginTop:23,marginBottom:10},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},link:{color:'#155EEF',fontWeight:'700',fontSize:13},quickRow:{flexDirection:'row',gap:9},quick:{flex:1,backgroundColor:'#fff',borderRadius:16,paddingVertical:13,alignItems:'center',borderWidth:1,borderColor:'#EAECF0'},quickIcon:{width:40,height:40,borderRadius:13,backgroundColor:'#EFF4FF',alignItems:'center',justifyContent:'center'},quickText:{fontSize:11,fontWeight:'700',color:'#344054',marginTop:7},item:{backgroundColor:'#fff',borderRadius:16,padding:13,marginBottom:8,flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:'#EAECF0'},itemIcon:{width:40,height:40,borderRadius:12,backgroundColor:'#FEF3F2',alignItems:'center',justifyContent:'center'},itemMain:{flex:1,marginLeft:11},itemTitle:{fontWeight:'700',color:'#101828',fontSize:14},itemSub:{fontSize:11,color:'#667085',marginTop:3},itemAmount:{fontWeight:'800',fontSize:12,color:'#101828',marginLeft:8},empty:{padding:22,backgroundColor:'#fff',borderRadius:16,borderWidth:1,borderColor:'#EAECF0'},emptyText:{color:'#667085',textAlign:'center',fontSize:13}});
